#!/usr/bin/env node
let path = require("path")
let fs = require("fs-extra")
let execa = require("execa")

let appsDirectory = "apps"

let getAppNames = () =>
  fs.readdir("apps")

let getAppPathFromName = name =>
  path.resolve(appsDirectory, name)

let getAppPaths = async () =>
  (await getAppNames()).map(getAppPathFromName)

let npmRun = (commandString, appName) => {
  let command = commandString.split(/\s+/)
  return execa("npm", [
    "run-script",
    "--prefix",
    getAppPathFromName(appName),
    "--scripts-prepend-node-path=true",
    ...command
  ], {
    extendEnv: true,
    env: {
      SNOOT_OUTPUT_DIRECTORY: "website",
      SNOOT_PUBLIC_URL: `/${appName}`
    }
  })
}

let mapNames = async fn => {
  let names = await getAppNames()
  let promises = names.map(name => fn(name))
  return Promise.all(promises)
}

let createTask = taskName => () =>
  mapNames(async name =>
    npmRun(
      taskName,
      name
    )
  )

exports.build = createTask("build")
exports.watch = createTask("watch")
exports.install = createTask("install")

let command = process.argv[2]

if (command) {
  createTask(command)()
}
