#!/usr/bin/env node
let path = require("path")
let fs = require("fs-extra")
let execa = require("execa")

let appsDirectory = "apps"

let getAppNames = () =>
  fs.readdir("apps")

let getAppPathFromName = name =>
  path.resolve(appsDirectory, name)

let getAppPaths = async () =>
  (await getAppNames()).map(getAppPathFromName)


let npmRun = (commandString, appPath) => {
  let command = commandString.split(/\s+/)
  return execa("npm", [
    "run-script",
    "--prefix",
    appPath,
    "--scripts-prepend-node-path=true",
    ...command
  ])
}

let mapNames = async fn => {
  let names = await getAppNames()
  let promises = names.map(name => fn(name))
  return Promise.all(promises)
}

exports.build = () =>
  mapNames(async name =>
    npmRun(
      `build -- -d website --public-url=/${name}`,
      getAppPathFromName(name)
    )
  )

exports.watch = () =>
  mapNames(async name =>
    npmRun(
      `watch -- -d website --public-url=/${name}`,
      getAppPathFromName(name)
    )
  )

exports.install = () =>
  mapNames(async name =>
    npmRun(
      "install",
      getAppPathFromName(name)
    )
  )

let command = exports[process.argv[2]]

command && command()